services:
  api:
    build: ./src/TransferenciasFinanceiras.Api
    container_name: transferencias-financeiras-api
    environment:
      ConnectionStrings__Padrao: "Host=host.docker.internal;Port=5432;Database=transferencias_financeiras;Username=postgres;Password=postgres"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "5080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        VITE_URL_API: http://localhost:5080
    container_name: transferencias-financeiras-tela
    ports:
      - "5173:80"
    depends_on:
      - api
    restart: unless-stopped
