// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TransferenciasFinanceiras.Api.Data;

#nullable disable

namespace TransferenciasFinanceiras.Api.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TransferenciasFinanceiras.Api.Model.Conta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("LimiteChequeEspecial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LimiteTransferenciaDiurno")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LimiteTransferenciaNoturno")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaxTentativasPorHoraDiurno")
                        .HasColumnType("integer");

                    b.Property<int>("MaxTentativasPorHoraNoturno")
                        .HasColumnType("integer");

                    b.Property<string>("NomeTitular")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Contas", (string)null);
                });

            modelBuilder.Entity("TransferenciasFinanceiras.Api.Model.Transferencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AgendadaPara")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdContaDestino")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdContaOrigem")
                        .HasColumnType("uuid");

                    b.Property<string>("MotivoFalha")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("ProcessadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdContaDestino");

                    b.HasIndex("IdContaOrigem");

                    b.HasIndex("Status", "AgendadaPara");

                    b.HasIndex("IdContaOrigem", "Status", "ProcessadaEm");

                    b.ToTable("Transferencias", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
